# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-16 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=b'', verbose_name='file')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
