# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-16 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='no value', max_length=80),
        ),
    ]
