# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-16 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapi', '0003_auto_20200716_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='uploads', verbose_name='file'),
        ),
    ]
