# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-16 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageapi', '0005_auto_20200716_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img',
        ),
    ]
