# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-16 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageapi', '0008_auto_20200716_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
